# -*- coding: utf-8 -*-
"""3D_scatter_plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sy0WqauIpbRWnRnUw23geoyEcePa1aGG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from plotly.offline import iplot
import plotly.graph_objs as go 

from google.colab import drive 
drive.mount('/content/drive')

timesData = pd.read_csv("/content/drive/MyDrive/timesData.csv")

timesData.head()

dataframe = timesData[timesData.year == 2015]

trace1 = go.Scatter3d(
    x=dataframe.world_rank,
    y=dataframe.research,
    z=dataframe.citations,
    mode='markers',
    marker=dict(
        size=dataframe.teaching,
        color='rgb(255,0,0)',
    )
)
data = [trace1]

layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=0,
    )
)
fig = go.Figure(data=data, layout=layout)

iplot(fig)