# -*- coding: utf-8 -*-
"""bar_plot_with_plotly.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1stjdjHzZwJY5AKccna62pJ9brpkF7y89
"""

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from plotly.offline import iplot
import plotly.graph_objs as go 

from google.colab import drive 
drive.mount('/content/drive')

timesData = pd.read_csv("/content/drive/MyDrive/timesData.csv")

timesData.head()

df2014 = timesData[timesData.year == 2014].iloc[:3,:]
df2014

trace1 = go.Bar(
        x = df2014.university_name,
        y = df2014.citations,
        name = "citations",
        marker = dict(color = 'rgba(255, 174, 255, 0.5)',
                      line=dict(color='rgb(0,0,0)',width=1.5)),
        text = df2014.country)

trace2 = go.Bar(
        x = df2014.university_name,  
        y = df2014.teaching,   
        name = "teaching",      
        marker = dict(color = 'rgba(255, 255, 128, 0.5)',   
                      line=dict(color='rgb(0,0,0)',width=1.5)), 
        text = df2014.country)  

data = [trace1, trace2]

layout = go.Layout(barmode = "group")

fig = go.Figure(data = data, layout = layout)

iplot(fig)

x = df2014.university_name

trace1 = {
    'x': x,
    'y': df2014.citations,
    'name': 'citation',
    'type': 'bar'
};
trace2 = {
    'x': x,
    'y': df2014.teaching,
    'name': 'teaching',
    'type': 'bar'
};

data = [trace1, trace2];

layout = {
    'xaxis': {'title': 'Top 3 universities'},
    'barmode': 'relative',
    'title': 'citations and teaching of top 3 unversities in 2014'
};

fig = go.Figure(data = data, layout = layout)

iplot(fig)