# -*- coding: utf-8 -*-
"""box_plot_with_plotly.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/128gOQ-5wm1HCawAKJF7yss8l9CBoeC1I
"""

import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from plotly.offline import iplot
import plotly.graph_objs as go

from google.colab import drive 
drive.mount('/content/drive')

timesData = pd.read_csv("/content/drive/MyDrive/timesData.csv")

timesData.head()

timesData.info()

x2015 = timesData[timesData.year == 2015]

international = [float(each) for each in x2015.international]

trace0 = go.Box(
    y=x2015.international,
    name = 'international score of universities in 2015',
    marker = dict(
        color = 'rgb(12, 12, 140)'
    )
)
trace1 = go.Box(
    y=x2015.research,
    name = 'research of universities in 2015',
    marker = dict(
        color = 'rgb(12, 128, 128)'
    )
)
data = [trace0, trace1]
iplot(data)