# -*- coding: utf-8 -*-
"""Linear_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AUH-NBRmXmXtPqNwnaEQiPp2_gfL5cIZ
"""

import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/linear_regression_dataset.csv")

df

df = pd.read_csv("/content/drive/MyDrive/linear_regression_dataset.csv", sep=";")

df.head()

plt.scatter(df.deneyim,df.maas)
plt.xlabel("Deneyim")
plt.ylabel("Maas")
plt.show()

x = df.deneyim.values

x.shape

x = df.deneyim.values.reshape(-1,1)
y = df.maas.values.reshape(-1,1)

from sklearn.linear_model import LinearRegression

linear_reg = LinearRegression()
linear_reg.fit(x,y)

import numpy as np 
b0 = linear_reg.predict([[0]])
print("b0: ",b0)

b0_ = linear_reg.intercept_
print("b0: ",b0_)

b1 = linear_reg.coef_
print("b1: ",b1)

new_salary = 1663 + 1138*11
print(new_salary)

b11 = linear_reg.predict([[11]])
print("b11: ",b11)

y_head = linear_reg.predict(x)

plt.plot(x, y_head, color="red")
plt.scatter(x,y)
plt.show()

from sklearn.metrics import r2_score
print("R Square Score: ", r2_score(y,y_head))

from sklearn.metrics import mean_squared_error
print("Mean Squared Error: ", mean_squared_error(y,y_head))

MSE = np.square(np.subtract(y,y_head)).mean()
print("Mean Squared Error: ", MSE)