# -*- coding: utf-8 -*-
"""normalization.pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TXaHzW6QRWSCDwU3_uZh7rjrk7TbcL13
"""

import pandas as pd 
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler

iris = load_iris()

iris_data = iris.data
iris_columns = iris.feature_names

iris_df = pd.DataFrame(data=iris_data, columns=iris_columns)

print(iris_df.head(30))

scaler = MinMaxScaler()
iris_df_scaled = scaler.fit_transform(iris_df)

iris_df_normalized = pd.DataFrame(data=iris_df_scaled, columns = iris_columns)
print(iris_df_normalized.head(30))

import seaborn as sns 
sns.pairplot(iris_df_normalized)