# -*- coding: utf-8 -*-
"""intomachinelearning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Eneskchmt/0563714f62075119cbf3b5032632d0d1/intomachinelearning.ipynb
"""

#listeler

list1 = [1,2,3,4,5]
type(list1)
print(list1)

list2 = ["enes","emre","eren"]
type(list2)
print(list2)

value = list1[2]
print(value)

value1 = list1[-2]
print(value1)

value3 =list2[0]
print(value3)

list1.append(6)
print(list1)

list1.remove(1)
print(list1)

list1.reverse()
print(list1)

#alt alta yazmak 

for each in range (1,9):
  print(each)

for each in "istanbul atakent":
  print(each)

#conditionals 
#if else statement

sayi1 = 30
sayi2 = 10

if(sayi1 < sayi2):
  print("sayi1 küçüktür sayi2'den")

elif(sayi1 == sayi2):

  print("sayi1 eşittir sayi2'ye")

else :

  print("sayi1 büyüktür sayi2'den")

def hesapla(x):
  output = x*x
  return output
sonuc = hesapla(5)
sonuc2 = lambda x: x*x
print(sonuc2(5))
y = 4
z = lambda x:x*y
z(4)

