# -*- coding: utf-8 -*-
"""scatter_plot_matrix_with_plotly.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CaHimur5dwJ_4ZOa9ZMrGEDvPnXHoDve
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from plotly.offline import iplot
import plotly.graph_objs as go
import plotly.figure_factory as ff

from google.colab import drive
drive.mount('/content/drive')

timesData = pd.read_csv("/content/drive/MyDrive/timesData.csv")

timesData.head()

dataframe = timesData[timesData.year == 2015]

data2015 = dataframe.loc[:,["research","citations","teaching"]]

data2015["index"] = np.arange(1,len(data2015)+1)

data2015.head()

fig = ff.create_scatterplotmatrix(
        data2015,
        diag='box',
        index='index',
        colormap='Portland',
        colormap_type='cat',
        height=700, width=700)
iplot(fig)